FLMikTekst = f'-    Prøv at lave en lys tone og derefter en dyb tone. \n-    Du kan også prøve at lave en lav lyd og derefter en høj lyd.\n-    Kan du se, hvad der ændrer sig på grafen?\nHer ses en graf, som viser lydstyrken af hver frekvens af lyd, der optages. På den vandrette akse kan alle \nfrekvenserne ses, og på den lodrette akse kan lydstyrken af hver af disse frekvenser ses. Man siger, at \nmennesker kan høre frekvenserne 20Hz - 20.000Hz. De fleste lyder, vi hører i hverdagen, har dog ret lave \nfrekvenser, så på denne graf kan du se frekvenserne 20Hz - 1.000Hz. Enheden Hz udtales som hertz og betyder, \nhvor mange gange, der sker en vibration i luften, hvert sekund.'

FLHøjtTekst = f'-    Prøv at afspille en lys tone og derefter en dyb tone. \n-    Du kan også prøve at afspille en lav lyd og derefter en høj lyd.\n-    Kan du se, hvad der ændrer sig på grafen?\nHer ses en graf, som viser lydstyrken af hver frekvens af lyd, der optages. Du kan afspille lyde med \nskyderne. På skyderne kan du vælge frekvensen, som styrer tonen, og lydstyrken af tre forskellige lyde. På \nden vandrette akse af grafen kan alle frekvenserne ses, og på den lodrette akse kan lydstyrken af hver af \ndisse frekvenser ses. Man siger at mennesker kan høre frekvenserne 20Hz - 20.000Hz. De fleste lyder, vi \nhører i hverdagen, har dog ret lave frekvenser, så på denne graf kan du se frekvenserne 20Hz - 1.000Hz. \nEnheden Hz udtales som hertz og betyder, hvor mange gange, der sker en vibration i luften, hvert sekund.'

LydbMikTekst = f'-    Prøv at lave en lys tone og derefter en dyb tone. \n-    Du kan også prøve at lave en lav lyd og derefter en høj lyd.\n-    Kan du se, hvad der ændrer sig på lydbølgen?\nHer ses den dominerende lydbølge, som mikrofonen optager. Den dominerende lydbølge viser lydbølgen af \nden højeste frekvens, mikrofonen kan hører. Højden af lydbølgen bliver kaldt for lydbølgens amplitude, og jo \nhøjere bølgen er, jo højere er den lyd, lydbølgen viser. Afstanden er mellem lydbølgens bølgetoppe kaldes \nbølgelængden, og jo kortere denne afstand er, jo højere er frekvensen.'

LydbHøjtTekst = f'-    Prøv at afspille en lys tone og derefter en dyb tone. \n-    Du kan også prøve at afspille en lav lyd og derefter en høj lyd.\n-    Kan du se, hvad der ændrer sig på lydbølgerne?\nHer ses tre lydbølger, af de lyde der bliver afspillet. Farverne på lydbølgerne og de skydere, \ndu kan indstille på, passer til hinanden. Du kan afspille lyde med skyderne. På skyderne kan du vælge \nfrekvensen, som styrer tonen, og lydstyrken af tre forskellige lyde. Højden af lydbølgerne bliver kaldt for \nlydbølgernes amplitude, og jo højere bølgerne er, jo højere er den lyd, lydbølgerne viser. Afstanden er \nmellem lydbølgernes bølgetoppe kaldes bølgelængden, og jo kortere denne afstand er, jo højere er frekvensen.'

TrykbMikTekst = f'-    Prøv at lave en lys tone og derefter en dyb tone. \n-    Du kan også prøve at lave en lav lyd og derefter en høj lyd.\n-    Kan du se, hvad der ændrer sig på trykbølgen?\nHer ses den trykbølge, der bliver produceret i luften, når der laves en lyd. Hver prik på denne illustration \nrepræsenterer et luftmolekyle, som er de bitte små byggesten, luft og alt andet er lavet af. Trykbølgerne i \nluften virker meget på samme måde som lydbølgerne. Jo større tæthe-den, som også bliver kaldt for \ndensiteten, er af luftmolekylerne, jo højere er lyden. Jo tættere trykbølgerne, som er samlinger af luft med \nhøj tæthed, er på hinanden, jo højere er frekvensen af lyden.'

TrykbHøjtTekst = f'-    Prøv at afspille en lys tone og derefter en dyb tone. \n-    Du kan også prøve at afspille en lav lyd og derefter en høj lyd.\n-    Kan du se, hvad der ændrer sig på trykbølgen?\nHer ses den trykbølge, der bliver produceret i luften, når der laves en lyd. Du kan afspille en lyd \nmed skyderne. På skyderne kan du vælge frekvensen, som styrer tonen, og lydstyrken af lyden. Hver prik på \ndenne illustration repræsenterer et luftmolekyle, som er de bitte små byggesten, luft og alt andet \ner lavet af. Trykbølgerne i luften virker meget på samme måde som lydbølgerne. Jo større tætheden, som også \nbliver kaldt for densiteten, er af luftmolekylerne, jo højere er lyden. Jo tættere trykbølgerne, som er \nsamlinger af luft med høj tæthed, er på hinanden, jo højere er frekvensen af lyden.'